name: RankPlugin
version: 1.0.1
api: [4.0.0, 5.0.0]
main: RanksPlus\RankPlugin
author: BajanDoesYT

commands:
  setrank:
    description: Set the rank of a player
    usage: /setrank <rank> <player>
    permission: ranksplus.setrank

permissions:
  ranksplus.setrank:
    description: Allows setting a player's rank
    default: op
